/* lidhra-bridge C ABI (Apple TV). Generated by hand; keep in sync with src/ffi.rs. */
#ifndef LIDHRA_BRIDGE_H
#define LIDHRA_BRIDGE_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ok = true: json is the command result. ok = false: json is {"error": "..."}.
   Called on a background thread; json is only valid during the call (copy it). */
typedef void (*LidhraCallback)(void *ctx, bool ok, const char *json);

/* Run a bridge command (see crates/lidhra-bridge/src/lib.rs for the table).
   args_json: a JSON object string, or NULL. Both strings are copied before return. */
void lidhra_bridge_call(const char *name, const char *args_json, void *ctx, LidhraCallback cb);

/* Static version string; never free it. */
const char *lidhra_bridge_version(void);

#ifdef __cplusplus
}
#endif

#endif /* LIDHRA_BRIDGE_H */
