#!/usr/bin/env bash
# tauri-cli writes a hardcoded `deploymentTarget: iOS 14.0` into the generated
# app/src-tauri/gen/apple/project.yml (and the resulting .xcodeproj), ignoring
# `bundle.iOS.minimumSystemVersion` in tauri.conf.json. The iOS 27.1 SDK (iPhone
# Duo) rejects a deployment target below 15.0, so every build fails until this is
# corrected. `gen/apple` is regenerated by `cargo tauri ios init`, so this runs
# AFTER init (locally and in CI) to make the setting durable. It patches both the
# xcodegen spec (project.yml) and the generated project.pbxproj directly, so it
# needs no xcodegen re-run and must run BEFORE any later pbxproj edit (e.g. the
# CI signing patch).
#
# Usage: scripts/ios-postgen.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONF="$ROOT/app/src-tauri/tauri.conf.json"
GEN="$ROOT/app/src-tauri/gen/apple"
PROJ="$GEN/project.yml"
PBX="$GEN/lidhra-desktop.xcodeproj/project.pbxproj"
[ -f "$CONF" ] || { echo "::error::ios-postgen: $CONF not found"; exit 1; }
[ -f "$PROJ" ] || { echo "::error::ios-postgen: $PROJ not found (run 'cargo tauri ios init' first)"; exit 1; }

# The single source of truth for the minimum OS is tauri.conf.json.
MIN="$(grep -oE '"minimumSystemVersion"[[:space:]]*:[[:space:]]*"[0-9.]+"' "$CONF" | grep -oE '[0-9]+\.[0-9]+' | head -1)"
MIN="${MIN:-15.0}"

# Bridge LIDHRA_DUO from this outer shell (where it is set) to the plugin's
# swift-rs build (where the env does not reach the Package.swift manifest): write
# a marker file the manifest checks. Present only for a Duo build; gitignored.
DUO_MARKER="$ROOT/app/src-tauri/plugins/native/ios/.lidhra_duo"
if [ -n "${LIDHRA_DUO:-}" ]; then
  touch "$DUO_MARKER"
  echo "ios-postgen: LIDHRA_DUO enabled (marker written)"
else
  rm -f "$DUO_MARKER"
fi

# 1) Keep the xcodegen spec consistent (in case the project is regenerated).
perl -0777 -i -pe "s/(deploymentTarget:\s*\n\s*iOS:\s*)[0-9.]+/\${1}$MIN/s" "$PROJ"
grep -qE "iOS:[[:space:]]*$MIN" "$PROJ" || { echo "::error::ios-postgen: project.yml not updated to $MIN"; exit 1; }

# 2) Patch the generated project directly so the change reaches the build now.
if [ -f "$PBX" ]; then
  perl -i -pe "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = $MIN;/g" "$PBX"
  if grep -qE "IPHONEOS_DEPLOYMENT_TARGET = 1[0-4]\.[0-9]+;" "$PBX"; then
    echo "::error::ios-postgen: pbxproj still targets below $MIN after patch"; exit 1
  fi
fi
echo "ios-postgen: iOS deployment target set to $MIN"

# 3) UIScene lifecycle adoption. The iOS 27 SDK traps at launch for an app with
# no scene manifest. Info.ios.plist carries it as the durable source, but ensure
# the generated Info.plist has it too, in case the init-time merge drops the key.
PLIST="$GEN/lidhra-desktop_iOS/Info.plist"
if [ -f "$PLIST" ] && ! /usr/libexec/PlistBuddy -c "Print :UIApplicationSceneManifest" "$PLIST" >/dev/null 2>&1; then
  # tao returns a scene configuration named "TaoScene" and sets its delegate
  # class programmatically, so the config is named here without a delegate class.
  /usr/libexec/PlistBuddy \
    -c "Add :UIApplicationSceneManifest dict" \
    -c "Add :UIApplicationSceneManifest:UIApplicationSupportsMultipleScenes bool false" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:UIWindowSceneSessionRoleApplication array" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:UIWindowSceneSessionRoleApplication:0 dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:UIWindowSceneSessionRoleApplication:0:UISceneConfigurationName string TaoScene" \
    "$PLIST" >/dev/null
  echo "ios-postgen: added UIApplicationSceneManifest (TaoScene)"
fi
