#!/usr/bin/env bash
# tauri-cli writes a hardcoded `deploymentTarget: iOS 14.0` into the generated
# app/src-tauri/gen/apple/project.yml (and the resulting .xcodeproj), ignoring
# `bundle.iOS.minimumSystemVersion` in tauri.conf.json. The iOS 27.1 SDK (iPhone
# Duo) rejects a deployment target below 15.0, so every build fails until this is
# corrected. `gen/apple` is regenerated by `cargo tauri ios init`, so this runs
# AFTER init (locally and in CI) to make the setting durable. It patches both the
# xcodegen spec (project.yml) and the generated project.pbxproj directly, so it
# needs no xcodegen re-run and must run BEFORE any later pbxproj edit (e.g. the
# CI signing patch).
#
# Usage: scripts/ios-postgen.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONF="$ROOT/app/src-tauri/tauri.conf.json"
GEN="$ROOT/app/src-tauri/gen/apple"
PROJ="$GEN/project.yml"
PBX="$GEN/lidhra-desktop.xcodeproj/project.pbxproj"
[ -f "$CONF" ] || { echo "::error::ios-postgen: $CONF not found"; exit 1; }
[ -f "$PROJ" ] || { echo "::error::ios-postgen: $PROJ not found (run 'cargo tauri ios init' first)"; exit 1; }

# The single source of truth for the minimum OS is tauri.conf.json.
MIN="$(grep -oE '"minimumSystemVersion"[[:space:]]*:[[:space:]]*"[0-9.]+"' "$CONF" | grep -oE '[0-9]+\.[0-9]+' | head -1)"
MIN="${MIN:-15.0}"

# 1) Keep the xcodegen spec consistent (in case the project is regenerated).
perl -0777 -i -pe "s/(deploymentTarget:\s*\n\s*iOS:\s*)[0-9.]+/\${1}$MIN/s" "$PROJ"
grep -qE "iOS:[[:space:]]*$MIN" "$PROJ" || { echo "::error::ios-postgen: project.yml not updated to $MIN"; exit 1; }

# 2) Patch the generated project directly so the change reaches the build now.
if [ -f "$PBX" ]; then
  perl -i -pe "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = $MIN;/g" "$PBX"
  if grep -qE "IPHONEOS_DEPLOYMENT_TARGET = 1[0-4]\.[0-9]+;" "$PBX"; then
    echo "::error::ios-postgen: pbxproj still targets below $MIN after patch"; exit 1
  fi
fi
echo "ios-postgen: iOS deployment target set to $MIN"
